### ISSUE TITLE
Optimize looks for phones

### ISSUE THREAD

**Issue by lordadamson** [Ketabuk/Ketabuk-Server#24]
it really looks, feels and behaves like utter shit on phones now look
![screenshot from 2016-06-16 20-36-19](https://cloud.githubusercontent.com/assets/6195060/16128732/96ef0ce2-340a-11e6-91a4-611d0dd5bc0a.png)

**Comment by Ahmed-Badawy** [comment]
don't do this until we have finished all of our work on the frontend. 
when the frontend is stable we can implement responsive layout functionality as we like. 

Append...
