### ISSUE TITLE
[Registration] Password Issue

### ISSUE THREAD

**Issue by AhmedHani** [Ketabuk/Ketabuk-Server#98]
It would be better if you set some constraints in choosing the password during registration phase. Like minimum length, ...etc.

**Comment by lordadamson** [comment]
That's a very sound suggestion. What constraints would you suggest?

**Comment by AhmedHani** [comment]
The constraints are usually in the string length and the characters used in the string. So, making the length is 8 as minimum. Also, using some symbols maybe be a must such as "-", numbers or capital letters.

Remember that, this is very important as the user may share some private and critical moment in his/her life. You need to make sure their account privacy.

**Comment by lordadamson** [comment]
I totally agree. 8 characters minimum and three of four (lowercase, uppercase, number, symbols).
